version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/data
    tty: true
    environment:
      - TERM=xterm-256color
      - RUST_BACKTRACE=1

  docs:
    build: docs
    volumes:
      - ./:/data
    tty: true
